package com.marlabs.rmbs.connector.report;

public class ExpenseReportQueries {
	
	public static final String findClaimsByProjectAndDateRange = "SELECT public.claimsubmit_header.claim_amount,"
			+ "	public.claimsubmit_header.claim_date,"
			+ "	public.claimsubmit_header.claim_no,"
			+ "	public.claimsubmit_header.period_from,"
		   + "	public.claimsubmit_header.period_to,"
		+ "	public.claimsubmit_header.project,"
		+ "	public.claimsubmit_header.remarks,"
		+ "	public.claimsubmit_header.total_expense,"
		+ "	public.claimsubmit_header.claim_type_id,"
		+ "	public.claimsubmit_header.currency_id,"
		+ "	public.claimsubmit_header.requesting_user_id,"
		+ "	public.claimsubmit_header.client_billable,"
		+ "	public.claimsubmit_header.final_status,"
		+ "	public.claimsubmit_header.approved_person_id,"
		+ "	public.currency_master.currency_code,"
		+ "	public.claimtype_master.claim_code,"
		+ "	public.claimtype_master.claim_desc,"
		+ "	requestedUser.cn as reqUsercn,"
		+ "	approverUser.cn as approverUserCn,"
		+ "	public.claimstatus_master.claim_status_code,"
		+ "	public.claimstatus_master.claim_status_desc"
		+ "    FROM public.claimsubmit_header"
		+ "	 INNER JOIN public.currency_master ON "
		+ "	 public.claimsubmit_header.currency_id = public.currency_master.id "
		+ "	 INNER JOIN public.claimtype_master ON "
		+ "	 public.claimsubmit_header.claim_type_id = public.claimtype_master.id "
		+ "	 INNER JOIN public.user_master as requestedUser ON public.claimsubmit_header.requesting_user_id = requestedUser.id "
		+ "	INNER JOIN public.user_master as approverUser ON  public.claimsubmit_header.approved_person_id = approverUser.id"
		+ "	INNER JOIN public.claimstatus_master ON "
		+ "	 public.claimsubmit_header.final_status = public.claimstatus_master.id"
		+ "		where public.claimsubmit_header.final_status<>1 and public.claimsubmit_header.final_status<>4 and public.claimsubmit_header.project_master_id=$P{projectId} and (public.claimsubmit_header.claim_date >= $P{fromDate}"
		+ "			and public.claimsubmit_header.claim_date <= $P{toDate})"; 
	
	public static final String findClaimsByDateRange = "SELECT public.claimsubmit_header.claim_amount,"
			+ "	public.claimsubmit_header.claim_date,"
			+ "	public.claimsubmit_header.claim_no,"
			+ "	public.claimsubmit_header.period_from,"
		   + "	public.claimsubmit_header.period_to,"
		+ "	public.claimsubmit_header.project,"
		+ "	public.claimsubmit_header.remarks,"
		+ "	public.claimsubmit_header.total_expense,"
		+ "	public.claimsubmit_header.claim_type_id,"
		+ "	public.claimsubmit_header.currency_id,"
		+ "	public.claimsubmit_header.requesting_user_id,"
		+ "	public.claimsubmit_header.client_billable,"
		+ "	public.claimsubmit_header.final_status,"
		+ "	public.claimsubmit_header.approved_person_id,"
		+ "	public.currency_master.currency_code,"
		+ "	public.claimtype_master.claim_code,"
		+ "	public.claimtype_master.claim_desc,"
		+ "	requestedUser.cn as reqUsercn,"
		+ "	approverUser.cn as approverUserCn,"
		+ "	public.claimstatus_master.claim_status_code,"
		+ "	public.claimstatus_master.claim_status_desc"
		+ "    FROM public.claimsubmit_header"
		+ "	 INNER JOIN public.currency_master ON "
		+ "	 public.claimsubmit_header.currency_id = public.currency_master.id "
		+ "	 INNER JOIN public.claimtype_master ON "
		+ "	 public.claimsubmit_header.claim_type_id = public.claimtype_master.id "
		+ "	 INNER JOIN public.user_master as requestedUser ON public.claimsubmit_header.requesting_user_id = requestedUser.id "
		+ "	INNER JOIN public.user_master as approverUser ON  public.claimsubmit_header.approved_person_id = approverUser.id"
		+ "	INNER JOIN public.claimstatus_master ON "
		+ "	 public.claimsubmit_header.final_status = public.claimstatus_master.id"
		+ "		where public.claimsubmit_header.final_status<>1 and public.claimsubmit_header.final_status<>4 and (public.claimsubmit_header.claim_date >= $P{fromDate}"
		+ "			and public.claimsubmit_header.claim_date <= $P{toDate})";
	
	
	public static final String findAllClaimsFromBeginning = "SELECT public.claimsubmit_header.claim_amount,"
			+ "	public.claimsubmit_header.claim_date,"
			+ "	public.claimsubmit_header.claim_no,"
			+ "	public.claimsubmit_header.period_from,"
		   + "	public.claimsubmit_header.period_to,"
		+ "	public.claimsubmit_header.project,"
		+ "	public.claimsubmit_header.remarks,"
		+ "	public.claimsubmit_header.total_expense,"
		+ "	public.claimsubmit_header.claim_type_id,"
		+ "	public.claimsubmit_header.currency_id,"
		+ "	public.claimsubmit_header.requesting_user_id,"
		+ "	public.claimsubmit_header.client_billable,"
		+ "	public.claimsubmit_header.final_status,"
		+ "	public.claimsubmit_header.approved_person_id,"
		+ "	public.currency_master.currency_code,"
		+ "	public.claimtype_master.claim_code,"
		+ "	public.claimtype_master.claim_desc,"
		+ "	requestedUser.cn as reqUsercn,"
		+ "	approverUser.cn as approverUserCn,"
		+ "	public.claimstatus_master.claim_status_code,"
		+ "	public.claimstatus_master.claim_status_desc"
		+ "    FROM public.claimsubmit_header"
		+ "	 INNER JOIN public.currency_master ON "
		+ "	 public.claimsubmit_header.currency_id = public.currency_master.id "
		+ "	 INNER JOIN public.claimtype_master ON "
		+ "	 public.claimsubmit_header.claim_type_id = public.claimtype_master.id "
		+ "	 INNER JOIN public.user_master as requestedUser ON public.claimsubmit_header.requesting_user_id = requestedUser.id "
		+ "	INNER JOIN public.user_master as approverUser ON  public.claimsubmit_header.approved_person_id = approverUser.id"
		+ "	INNER JOIN public.claimstatus_master ON "
		+ "	 public.claimsubmit_header.final_status = public.claimstatus_master.id"
		+ "		where public.claimsubmit_header.final_status<>1 and public.claimsubmit_header.final_status<>4  and ("
		+ "			public.claimsubmit_header.claim_date <= $P{toDate})"; 
	
	
	
	public static final String findClaimsByProjectFromBeginning = "SELECT public.claimsubmit_header.claim_amount,"
			+ "	public.claimsubmit_header.claim_date,"
			+ "	public.claimsubmit_header.claim_no,"
			+ "	public.claimsubmit_header.period_from,"
		   + "	public.claimsubmit_header.period_to,"
		+ "	public.claimsubmit_header.project,"
		+ "	public.claimsubmit_header.remarks,"
		+ "	public.claimsubmit_header.total_expense,"
		+ "	public.claimsubmit_header.claim_type_id,"
		+ "	public.claimsubmit_header.currency_id,"
		+ "	public.claimsubmit_header.requesting_user_id,"
		+ "	public.claimsubmit_header.client_billable,"
		+ "	public.claimsubmit_header.final_status,"
		+ "	public.claimsubmit_header.approved_person_id,"
		+ "	public.currency_master.currency_code,"
		+ "	public.claimtype_master.claim_code,"
		+ "	public.claimtype_master.claim_desc,"
		+ "	requestedUser.cn as reqUsercn,"
		+ "	approverUser.cn as approverUserCn,"
		+ "	public.claimstatus_master.claim_status_code,"
		+ "	public.claimstatus_master.claim_status_desc"
		+ "    FROM public.claimsubmit_header"
		+ "	 INNER JOIN public.currency_master ON "
		+ "	 public.claimsubmit_header.currency_id = public.currency_master.id "
		+ "	 INNER JOIN public.claimtype_master ON "
		+ "	 public.claimsubmit_header.claim_type_id = public.claimtype_master.id "
		+ "	 INNER JOIN public.user_master as requestedUser ON public.claimsubmit_header.requesting_user_id = requestedUser.id "
		+ "	INNER JOIN public.user_master as approverUser ON  public.claimsubmit_header.approved_person_id = approverUser.id"
		+ "	INNER JOIN public.claimstatus_master ON "
		+ "	 public.claimsubmit_header.final_status = public.claimstatus_master.id"
		+ "		where public.claimsubmit_header.final_status<>1 and public.claimsubmit_header.final_status<>4 and public.claimsubmit_header.project_master_id=$P{projectId} and ("
		+ "			public.claimsubmit_header.claim_date <= $P{toDate})"; 
}
